### ISSUE TITLE
关于VuiLib开发的一些建议

### ISSUE THREAD

**Issue by ChenPi11** [FSMargoo/VuiLib#10]
# 关于VuiLib开发的一些建议
# 仓库
+ 开发时不建议直接将更改推送到origin/main中，建议每个版本开发时推送到origin/dev中，当新的版本发布时用Pull Request把origin/dev merge到 origin/main中
  - 意义：有利于使main分支更加整洁，直接更改main分支一般是危险的，使用上述方法，不仅符合惯例，而且方便版本的回滚（只用撤回一个merge提交），并且使用dev分支可以保证main的稳定性，**当以后项目main分支出现问题时（比如想完全撤回这个版本的所有提交），只用撤一个merge提交而不是一堆小提交**

# 项目结构，源文件，项目管理
+ 您的变量命名规范偏向大驼峰或匈牙利命名法，这样可能不利于阅读，建议类型名大驼峰，其他的下划线命名法即可。
+ 您的代码过于贴近WinAPI（例如 https://github.com/FSMargoo/VuiLib/blob/main/include/win32base/vwin32base.h ）
```cpp
void VWin32MsgThread(const int &Width, const int &Height, LPCWSTR WindowTitle, LPCWSTR ClassName, HWND ParentWindow);
```
有些修饰是没必要的（编译器其实会有所忽略），有些类型名是WinAPI提供的，建议**尽量**使用C++标准的类型名，这和WinAPI是兼容的，可以改成这样（int建议使用size_t，这东西更常用）
```cpp
void VWin32MsgThread(size_t width, size_t height, const wchar_t* window_title, const wchar_t* class_name, HWND parent_window);
```

# 生成/编译
+ 仓库编写一个准备Release和编译生成Release的脚本
+ 仓库以后可以使用GitHub CI编译，这个又快又方便，还完全免费

# 另外
+ 我在中考结束后会考虑参与开发
+ 我希望未来将VuiLib作为C++ Plus包发布（C++ Plus是我的项目，类似于您的stl-ex，但是功能要强大很多，目前未完成），不知您是否愿意
+ 我的开发经验也不多，这些建议可以有所取舍 :)

谢谢
2023/6/5

**Comment by FSMargoo** [comment]
我先说关于“类型名大驼峰”的考虑吧，我个人认为这是降低可读性的，考虑到现代 IDE 不需要特别在变量名中加上类型（当然不考虑有很多程序员有这个阅读习惯，但是事实上因为 VuiLib 目前只是我一个人开发，所以无所谓，但是这个类型名没有必要性），而因为 VuiLib 只针对 Windows 平台，所以贴近 WINAPI 没有任何问题，而且你猜猜为啥要给他开个 vwin32base.h，而 Release 知识懒得开而已，仓库管理我也会在我中考完后进行整理，至于 C++ Plus 的这件事情，VuiLib 是 MIT 协议，所以随便，你甚至可以 fork 一个改名成 BUILib 说是你自己写的都行... 其他的，再等中考完深入考虑

**Comment by ScSofts** [comment]
> # 关于VuiLib开发的一些建议
> # 仓库
> + 开发时不建议直接将更改推送到origin/main中，建议每个版本开发时推送到origin/dev中，当新的版本发布时用Pull Request把origin/dev merge到 origin/main中
>   - 意义：有利于使main分支更加整洁，直接更改main分支一般是危险的，使用上述方法，不仅符合惯例，而且方便版本的回滚（只用撤回一个merge提交），并且使用dev分支可以保证main的稳定性，**当以后项目main分支出现问题时（比如想完全撤回这个版本的所有提交），只用撤一个merge提交而不是一堆小提交**
> 
> # 项目结构，源文件，项目管理
> + 您的变量命名规范偏向大驼峰或匈牙利命名法，这样可能不利于阅读，建议类型名大驼峰，其他的下划线命名法即可。
> + 您的代码过于贴近WinAPI（例如 https://github.com/FSMargoo/VuiLib/blob/main/include/win32base/vwin32base.h ）
> ```cpp
> void VWin32MsgThread(const int &Width, const int &Height, LPCWSTR WindowTitle, LPCWSTR ClassName, HWND ParentWindow);
> ```
> 有些修饰是没必要的（编译器其实会有所忽略），有些类型名是WinAPI提供的，建议**尽量**使用C++标准的类型名，这和WinAPI是兼容的，可以改成这样（int建议使用size_t，这东西更常用）
> ```cpp
> void VWin32MsgThread(size_t width, size_t height, const wchar_t* window_title, const wchar_t* class_name, HWND parent_window);
> ```
> 
> # 生成/编译
> + 仓库编写一个准备Release和编译生成Release的脚本
> + 仓库以后可以使用GitHub CI编译，这个又快又方便，还完全免费
> 
> # 另外
> + 我在中考结束后会考虑参与开发
> + 我希望未来将VuiLib作为C++ Plus包发布（C++ Plus是我的项目，类似于您的stl-ex，但是功能要强大很多，目前未完成），不知您是否愿意
> + 我的开发经验也不多，这些建议可以有所取舍 :)
> 
> 谢谢
> 2023/6/5
> 


Git Flow工作流是个好建议

**Comment by vanehu** [comment]
> # 关于VuiLib开发的一些建议
> # 仓库
> * 开发时不建议直接将更改推送到origin/main中，建议每个版本开发时推送到origin/dev中，当新的版本发布时用Pull Request把origin/dev merge到 origin/main中
>   
>   * 意义：有利于使main分支更加整洁，直接更改main分支一般是危险的，使用上述方法，不仅符合惯例，而且方便版本的回滚（只用撤回一个merge提交），并且使用dev分支可以保证main的稳定性，**当以后项目main分支出现问题时（比如想完全撤回这个版本的所有提交），只用撤一个merge提交而不是一堆小提交**
> 
> # 项目结构，源文件，项目管理
> * 您的变量命名规范偏向大驼峰或匈牙利命名法，这样可能不利于阅读，建议类型名大驼峰，其他的下划线命名法即可。
> * 您的代码过于贴近WinAPI（例如 https://github.com/FSMargoo/VuiLib/blob/main/include/win32base/vwin32base.h ）
> 
> ```c++
> void VWin32MsgThread(const int &Width, const int &Height, LPCWSTR WindowTitle, LPCWSTR ClassName, HWND ParentWindow);
> ```
> 
> 有些修饰是没必要的（编译器其实会有所忽略），有些类型名是WinAPI提供的，建议**尽量**使用C++标准的类型名，这和WinAPI是兼容的，可以改成这样（int建议使用size_t，这东西更常用）
> 
> ```c++
> void VWin32MsgThread(size_t width, size_t height, const wchar_t* window_title, const wchar_t* class_name, HWND parent_window);
> ```
> 
> # 生成/编译
> * 仓库编写一个准备Release和编译生成Release的脚本
> * 仓库以后可以使用GitHub CI编译，这个又快又方便，还完全免费
> 
> # 另外
> * 我在中考结束后会考虑参与开发
> * 我希望未来将VuiLib作为C++ Plus包发布（C++ Plus是我的项目，类似于您的stl-ex，但是功能要强大很多，目前未完成），不知您是否愿意
> * 我的开发经验也不多，这些建议可以有所取舍 :)
> 
> 谢谢 2023/6/5

中考？？？？ 中学生？？？ 你不要太过分啊
