### ISSUE TITLE
IDontKnow 编译错误

### ISSUE THREAD

**Issue by wuwao1** [FSMargoo/VuiLib#11]
`Error	C2039	'SetPlaneText': is not a member of 'Core::VTextLabel'`
**SetPlaneText**应全局替换成**SetPlainText**

**Comment by wuwao1** [comment]
`Error	C3861	'GetPlaneText': identifier not found	vml-editor`
**GetPlaneText**应全局替换成 **GetPlainText**

**Comment by FSMargoo** [comment]
Yes, some stupid problems...

**Comment by FSMargoo** [comment]
Already changed... close........... :(
