### ISSUE TITLE
Skia 版本

### ISSUE THREAD

**Issue by ddkwork** [FSMargoo/VuiLib#12]
你好，您使用的skia版本或者提交id，分支名称是什么

**Comment by FSMargoo** [comment]
您好，我使用的是修改过的 $Skia$ $M101$。但基于 UI 库实际功能需求，我自行修改了 $M101$ 中有关 $SkSL$ 解析的部分源码，使之支持宏定义以及 \# $alias$ 命令。
若您有兴趣，可以在[这个仓库](https://github.com/FSMargoo/SkiaM101Binary)中找到我修改过后的源码以及针对 MSVC 平台的预编译版本。

**Comment by ddkwork** [comment]
好的，我刚刚才发现您的修改，已经编译通过了。

我是通过搜索glfw和skia的配合找到您的库，起因是目前我使用一个go绑定skia m127的ui库，在调试模式下无法呈现界面，但直接运行是ok的。报错显示gl句柄无效，不支持转换操作。

谢谢您的库，我将通过调试看能不能找到bug。

因为go版本的实现和您的实现原理是一样的:glfw创建窗口，然后通过skia绘图回调把上下文返回给gl。
