### ISSUE TITLE
CPU占用过高，需要优化

### ISSUE THREAD

**Issue by woddle** [FSMargoo/VuiLib#2]
图像查看器程序，在加载了程序后，CPU占用一直在20%，也不会下降

**Comment by FSMargoo** [comment]
能不能提供一下具体的操作，是打开程序后不进行任何操作就一直占用 CPU，还是加载了图片以后占用 CPU？

**Comment by woddle** [comment]
1、编译demo里面的PhotoViewerX，然后启动；CPU占用很低
2、随便加载一张图像，此时CPU占用涨到10%以上，并且没有任何操作，一直占用这么高不会下降。

**Comment by FSMargoo** [comment]
问题已经解决了，出现的原因是因为调用了 GetOpenFileName 没有即时释放资源导致一直占用 CPU...
