### ISSUE TITLE
Add CMakeLists.txt

### ISSUE THREAD

**Issue by hgntn** [FSMargoo/VuiLib#4]
This will support building with cmake.

**Comment by ScSofts** [comment]
？Did you read README.md?

**Comment by FSMargoo** [comment]
CMakeLists.txt was added into VuiLib for a short time, but after a while I decided to delete it just because i dont consider that someone really need a CMakeLists.txt for a msvc only project....

**Comment by hgntn** [comment]
> CMakeLists.txt was added into VuiLib for a short time, but after a while I decided to delete it just because i dont consider that someone really need a CMakeLists.txt for a msvc only project....

Yep, I think the same too. Please put it clear on README.md that your project is MSVC only. Thank you.

**Comment by FSMargoo** [comment]
Yes... that's a mistake of my work :(

**Comment by FSMargoo** [comment]
VUILib has been changed to the CMake build system.
