### ISSUE TITLE
Support MinGW-w64 on MSYS2

### ISSUE THREAD

**Issue by hgntn** [FSMargoo/VuiLib#5]
The open source compiler has some limitations compared to MSVC. For example, if you are using technology like ATL or MFC then it will not work on MinGW-w64 because it has no support for them. On MinGW-w64, people use Win32++ as an alternative:

https://win32-framework.sourceforge.net/

**Comment by FSMargoo** [comment]
What you said is a reason to support MinGW-w64 on MSYS2, but I don't have any experience in coding with MinGW-w64, so... maybe later...

**Comment by FSMargoo** [comment]
In VUILib 3.x, we already supported the other compiler like clang or gcc(Whether operation system your are). It can pass the build test and unit test under my PC with manjaro.
