### ISSUE TITLE
建议重新组织一下解决方案，

### ISSUE THREAD

**Issue by KnIfER** [FSMargoo/VuiLib#6]
建议主库生成lib，成为demo项目的依赖。

将demo都并入一个sln，统一用props属性文件进行管理。

![image (3)](https://user-images.githubusercontent.com/11593903/228184044-0ec154b4-e156-46b5-9298-39898f32fbd2.png)

**Comment by ScSofts** [comment]
建议用cmake

**Comment by ScSofts** [comment]
他**可能**没什么空，你组织下提个pr就好

**Comment by FSMargoo** [comment]
主库生成 lib 这个有点困难，主要是一开始没有定义类似 VLIB_API 这样的导出宏，如果要生成 lib 的话要不然写一堆 .def 文件要不然每个加上导出宏，还是挺麻烦的

**Comment by FSMargoo** [comment]
近期找个时间解决一下

**Comment by KnIfER** [comment]
不用导出，静态库是和原来一样使用的。等我上传一下，不过我是基于旧的commit改的，改掉了黑框。

**Comment by FSMargoo** [comment]
好的

**Comment by KnIfER** [comment]
https://github.com/appxmod/vuilib

**Comment by FSMargoo** [comment]
我看看
