### ISSUE TITLE
【feature】编辑框控件能不能加入汉语词组分词？

### ISSUE THREAD

**Issue by KnIfER** [FSMargoo/VuiLib#7]
安卓的汉语词组分词可以用icu4j中的BreakIterator实现。icu也有c语言的库。能不能实现chrome输入框的双击选中汉语词组的特性呢？如果有将会很方便。

**Comment by ScSofts** [comment]
能否提供原理或demo

**Comment by KnIfER** [comment]
demo我还拿不出来，见谅。只在java调用过。

其实可以先实现一下双击选择，简单检测下中英文边界、标点符号等，预留个接口，可以的话以后再上icu4c。

**Comment by FSMargoo** [comment]
已经预留了一个接口了，highlight 类就支持了对应语言的双击选中，而对于汉字或是简单的标点符号选中，预计会在后期支持

**Comment by KnIfER** [comment]
小哥，删库啦？！
。。

**Comment by FSMargoo** [comment]
> 小哥，删库啦？！ 。。

没有啦，我只是在重构准备 VUILIB3 的内容而已，因为 VUILIB3 要全部重写，所以自然代码都没啦，如果任然需要 2.x.x 的代码依然可以在分支里查看哦

**Comment by FSMargoo** [comment]
顺带一提，该 feature 应该会在 VUILIB3 中以 plugin 形式被实现

**Comment by KnIfER** [comment]
哦哦。

有没有兴趣换个IDE。jetbrain 的 clion，重构、查看代码应该很方便。

**Comment by FSMargoo** [comment]
VUILIB 在一年前就已经申请到了 JetBrains 的开源计划并获取了全套 JetBrains 软件的开源授权。我也一直在尝试这个 IDE。感谢推荐。
