### ISSUE TITLE
关于将 VuiLib 更名为 LibVui 的一些建议

### ISSUE THREAD

**Issue by ChenPi11** [FSMargoo/VuiLib#9]
# 关于将 VuiLib 更名为 LibVui 的一些建议
+ 你的库名 VuiLib 虽然易于记忆， **但不符合通用的命名规范** ，可能会影响到其他开发者的使用和扩展。
+ 建议将其更名为 LibVui ，这样更容易被其他开发者识别和使用。同时，更名也可以使你的库更加规范和易于维护。
+ CMake 编译库时，会自动将库命名为 'lib+${PROJECT_NAME}' ，如果使用 CMake 编译 VuiLib ，最后可能会出现一个叫 libVuiLib.dll 的动态链接库，这和使用MSBuild编译的结果是不兼容的，通常库的编译要避免这种情况出现。 CMake 是当今十分常用的 C/C++ 程序编译方式，因为MSBuild几乎不可移植（甚至可能无法移植到 MinGW 上）。
+ 使用 GNU Autoconf/Libtool 进行编译时，**库名称必须以 'lib\*\*\*' 开头**，否则无法通过编译。
+ 在使用 GNU GCC 链接已安装的库时 'gcc -l<library>' ，会查找安装路径中以 'lib' 开头的动态库，如果编译出来的是 'VuiLib.dll' 或 'VuiLib.a(.lib)' ，则在 MinGW 上执行 'gcc -lVuiLib' 可能会**链接失败**。

综上所述，我认为将 VuiLib 更名为 LibVui 更好，毕竟这样更适合开发者辨识，且 libVuiLib 这个名字好像不太好听。
谢谢
2023/6/5

**Comment by FSMargoo** [comment]
Actually, we just need to change the output file name into $libvui$ to solve the above problems, which dose not require to change the name of this project.
